baseURL = "https://customtwemoji.com/"
title = "Custom Twemoji API"
enableRobotsTXT = true

# edit this if you'ld rather use a fork of this repo
theme = ["github.com/onweru/compose"]

# if you prefer to load the theme normally
# theme = "compose"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  localApi = "http://localhost"
  productionApi = "https://customtwemojiapi.com"
  randomFaceEndpoint = "/v1/faces/random?output=image&file_format=svg&background_color=transparent"

[outputs]
  home = ["HTML", "RSS","JSON"]

[module]
[[module.imports]]
  path = "github.com/jakejarvis/hugo-mod-twemoji"
