baseURL = "https://customtwemoji.com/"
title = "Custom Twemoji API"
enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

# edit this if you'ld rather use a fork of this repo
# theme = ["github.com/onweru/compose"]

# if you prefer to load the theme normally
# theme = "compose"

[module]
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = "github.com/onweru/compose"
[[module.imports]]
  disable = false
  ignoreConfig = false
  ignoreImports = false
  path = "github.com/jakejarvis/hugo-mod-twemoji"

enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
