#  menu items
[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

# [[main]]
#   name = "Tutorials"
#   weight = 2
#   url = "tutorials/"

[[main]]
  name = "Random Example"
  weight = 3
  url = "https://customtwemojiapi.com/v1/faces/random?output=image&file_format=png&size=500"
