name: Percy on GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
        
      - name: Send Percy snapshots
        run: npx @percy/cli snapshot .
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
